name = "cursor-sharing"
main = "./cursor.ts"
compatibility_date = "2025-04-09"

[durable_objects]
bindings = [
  { name = "CURSOR_ROOM", class_name = "CursorRoom" },
]

[[migrations]]
tag = "v1"
new_classes = ["CursorRoom"]
